# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/direct_factoring_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_direct_factoring(object):
    def setupUi(self, direct_factoring):
        direct_factoring.setObjectName("direct_factoring")
        direct_factoring.resize(850, 650)
        direct_factoring.setMinimumSize(QtCore.QSize(850, 650))
        direct_factoring.setMaximumSize(QtCore.QSize(850, 650))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        direct_factoring.setPalette(palette)
        self.label = QtWidgets.QLabel(direct_factoring)
        self.label.setGeometry(QtCore.QRect(40, 30, 771, 161))
        self.label.setStyleSheet("background-image: url(:/images/Banner6.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.doolittle_button = QtWidgets.QPushButton(direct_factoring)
        self.doolittle_button.setGeometry(QtCore.QRect(250, 250, 361, 61))
        self.doolittle_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.doolittle_button.setObjectName("doolittle_button")
        self.crout_button = QtWidgets.QPushButton(direct_factoring)
        self.crout_button.setGeometry(QtCore.QRect(250, 360, 361, 61))
        self.crout_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.crout_button.setObjectName("crout_button")
        self.cholesky_button = QtWidgets.QPushButton(direct_factoring)
        self.cholesky_button.setGeometry(QtCore.QRect(250, 470, 361, 61))
        self.cholesky_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.cholesky_button.setObjectName("cholesky_button")
        self.back_button = QtWidgets.QPushButton(direct_factoring)
        self.back_button.setGeometry(QtCore.QRect(20, 580, 80, 50))
        self.back_button.setStyleSheet("background-color: rgb(0, 86, 145);\n"
"background-image: url(:/images/back.png);")
        self.back_button.setText("")
        self.back_button.setIconSize(QtCore.QSize(80, 50))
        self.back_button.setObjectName("back_button")
        self.home_button = QtWidgets.QPushButton(direct_factoring)
        self.home_button.setGeometry(QtCore.QRect(740, 580, 80, 50))
        self.home_button.setStyleSheet("background-color: rgb(0, 86, 145);\n"
"background-image: url(:/images/home.png);")
        self.home_button.setText("")
        self.home_button.setIconSize(QtCore.QSize(80, 50))
        self.home_button.setObjectName("home_button")

        self.retranslateUi(direct_factoring)
        QtCore.QMetaObject.connectSlotsByName(direct_factoring)

    def retranslateUi(self, direct_factoring):
        _translate = QtCore.QCoreApplication.translate
        direct_factoring.setWindowTitle(_translate("direct_factoring", "Form"))
        self.doolittle_button.setText(_translate("direct_factoring", "Doolittle"))
        self.crout_button.setText(_translate("direct_factoring", "Crout"))
        self.cholesky_button.setText(_translate("direct_factoring", "Cholesky"))
import link_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    direct_factoring = QtWidgets.QWidget()
    ui = Ui_direct_factoring()
    ui.setupUi(direct_factoring)
    direct_factoring.show()
    sys.exit(app.exec_())
