# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/full_pivoting_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_full_pivoting(object):
    def setupUi(self, full_pivoting):
        full_pivoting.setObjectName("full_pivoting")
        full_pivoting.resize(900, 700)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        full_pivoting.setPalette(palette)
        self.label = QtWidgets.QLabel(full_pivoting)
        self.label.setGeometry(QtCore.QRect(60, 20, 771, 161))
        self.label.setStyleSheet("background-image: url(:/images/Banner11.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(full_pivoting)
        self.label_5.setGeometry(QtCore.QRect(80, 200, 81, 41))
        self.label_5.setStyleSheet("background-image: url(:/images/n.png);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Designer\\../UserInterface/Util/Images/n.png"))
        self.label_5.setObjectName("label_5")
        self.n_input = QtWidgets.QTextEdit(full_pivoting)
        self.n_input.setGeometry(QtCore.QRect(220, 200, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.n_input.setFont(font)
        self.n_input.setObjectName("n_input")
        self.matrix_button = QtWidgets.QPushButton(full_pivoting)
        self.matrix_button.setGeometry(QtCore.QRect(370, 200, 171, 51))
        self.matrix_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.matrix_button.setObjectName("matrix_button")

        self.retranslateUi(full_pivoting)
        QtCore.QMetaObject.connectSlotsByName(full_pivoting)

    def retranslateUi(self, full_pivoting):
        _translate = QtCore.QCoreApplication.translate
        full_pivoting.setWindowTitle(_translate("full_pivoting", "Form"))
        self.matrix_button.setText(_translate("full_pivoting", "Generate Matrix"))
import link_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    full_pivoting = QtWidgets.QWidget()
    ui = Ui_full_pivoting()
    ui.setupUi(full_pivoting)
    full_pivoting.show()
    sys.exit(app.exec_())
