# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/gaussian_elim_simple_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


