# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/gauss_seidel_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gauss_seidel(object):
    def setupUi(self, gauss_seidel):
        gauss_seidel.setObjectName("gauss_seidel")
        gauss_seidel.resize(900, 700)
        gauss_seidel.setMinimumSize(QtCore.QSize(900, 700))
        gauss_seidel.setMaximumSize(QtCore.QSize(900, 700))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        gauss_seidel.setPalette(palette)
        self.label = QtWidgets.QLabel(gauss_seidel)
        self.label.setGeometry(QtCore.QRect(60, 20, 771, 161))
        self.label.setStyleSheet("image: url(:/images/gausseidel_anner.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(gauss_seidel)
        self.label_5.setGeometry(QtCore.QRect(50, 200, 81, 41))
        self.label_5.setStyleSheet("background-image: url(:/images/n.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.n_input = QtWidgets.QTextEdit(gauss_seidel)
        self.n_input.setGeometry(QtCore.QRect(120, 200, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.n_input.setFont(font)
        self.n_input.setObjectName("n_input")
        self.matrix_button = QtWidgets.QPushButton(gauss_seidel)
        self.matrix_button.setGeometry(QtCore.QRect(230, 200, 171, 51))
        self.matrix_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.matrix_button.setObjectName("matrix_button")
        self.run_button = QtWidgets.QPushButton(gauss_seidel)
        self.run_button.setGeometry(QtCore.QRect(380, 630, 151, 51))
        self.run_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.run_button.setObjectName("run_button")
        self.t_input = QtWidgets.QTextEdit(gauss_seidel)
        self.t_input.setGeometry(QtCore.QRect(520, 200, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t_input.setFont(font)
        self.t_input.setObjectName("t_input")
        self.label_2 = QtWidgets.QLabel(gauss_seidel)
        self.label_2.setGeometry(QtCore.QRect(470, 200, 71, 41))
        self.label_2.setStyleSheet("image: url(:/images/t.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.iter_input = QtWidgets.QTextEdit(gauss_seidel)
        self.iter_input.setGeometry(QtCore.QRect(780, 200, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.iter_input.setFont(font)
        self.iter_input.setObjectName("iter_input")
        self.label_3 = QtWidgets.QLabel(gauss_seidel)
        self.label_3.setGeometry(QtCore.QRect(710, 200, 71, 41))
        self.label_3.setStyleSheet("image: url(:/images/nmax.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(gauss_seidel)
        QtCore.QMetaObject.connectSlotsByName(gauss_seidel)

    def retranslateUi(self, gauss_seidel):
        _translate = QtCore.QCoreApplication.translate
        gauss_seidel.setWindowTitle(_translate("gauss_seidel", "Form"))
        self.matrix_button.setText(_translate("gauss_seidel", "Generate Matrix"))
        self.run_button.setText(_translate("gauss_seidel", "Run method"))
import link_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gauss_seidel = QtWidgets.QWidget()
    ui = Ui_gauss_seidel()
    ui.setupUi(gauss_seidel)
    gauss_seidel.show()
    sys.exit(app.exec_())
