# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/gaussian_elimination_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gaussian_elimination(object):
    def setupUi(self, gaussian_elimination):
        gaussian_elimination.setObjectName("gaussian_elimination")
        gaussian_elimination.resize(850, 650)
        gaussian_elimination.setMinimumSize(QtCore.QSize(850, 650))
        gaussian_elimination.setMaximumSize(QtCore.QSize(850, 650))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        gaussian_elimination.setPalette(palette)
        self.label = QtWidgets.QLabel(gaussian_elimination)
        self.label.setGeometry(QtCore.QRect(40, 30, 771, 161))
        self.label.setStyleSheet("background-image: url(:/images/Banner9.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.simple_button = QtWidgets.QPushButton(gaussian_elimination)
        self.simple_button.setGeometry(QtCore.QRect(240, 270, 391, 51))
        self.simple_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.simple_button.setObjectName("simple_button")
        self.partial_button = QtWidgets.QPushButton(gaussian_elimination)
        self.partial_button.setGeometry(QtCore.QRect(240, 360, 391, 51))
        self.partial_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.partial_button.setObjectName("partial_button")
        self.full_button = QtWidgets.QPushButton(gaussian_elimination)
        self.full_button.setGeometry(QtCore.QRect(240, 450, 391, 51))
        self.full_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.full_button.setObjectName("full_button")
        self.back_button = QtWidgets.QPushButton(gaussian_elimination)
        self.back_button.setGeometry(QtCore.QRect(20, 580, 80, 50))
        self.back_button.setStyleSheet("background-color: rgb(0, 86, 145);\n"
"background-image: url(:/images/back.png);")
        self.back_button.setText("")
        self.back_button.setIconSize(QtCore.QSize(80, 50))
        self.back_button.setObjectName("back_button")
        self.home_button = QtWidgets.QPushButton(gaussian_elimination)
        self.home_button.setGeometry(QtCore.QRect(740, 580, 80, 50))
        self.home_button.setStyleSheet("background-color: rgb(0, 86, 145);\n"
"background-image: url(:/images/home.png);")
        self.home_button.setText("")
        self.home_button.setIconSize(QtCore.QSize(80, 50))
        self.home_button.setObjectName("home_button")

        self.retranslateUi(gaussian_elimination)
        QtCore.QMetaObject.connectSlotsByName(gaussian_elimination)

    def retranslateUi(self, gaussian_elimination):
        _translate = QtCore.QCoreApplication.translate
        gaussian_elimination.setWindowTitle(_translate("gaussian_elimination", "Form"))
        self.simple_button.setText(_translate("gaussian_elimination", "Simple Gaussian Elimination"))
        self.partial_button.setText(_translate("gaussian_elimination", "Gaussian Elimination with Partial Pivoting"))
        self.full_button.setText(_translate("gaussian_elimination", "Gaussian Elimination with Full Pivoting"))
import link_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gaussian_elimination = QtWidgets.QWidget()
    ui = Ui_gaussian_elimination()
    ui.setupUi(gaussian_elimination)
    gaussian_elimination.show()
    sys.exit(app.exec_())
