# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/home_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_home_window(object):
    def setupUi(self, home_window):
        home_window.setObjectName("home_window")
        home_window.resize(850, 650)
        home_window.setMinimumSize(QtCore.QSize(850, 650))
        home_window.setMaximumSize(QtCore.QSize(850, 650))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        home_window.setPalette(palette)
        self.methods_button = QtWidgets.QPushButton(home_window)
        self.methods_button.setGeometry(QtCore.QRect(20, 560, 191, 61))
        self.methods_button.setAcceptDrops(False)
        self.methods_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.methods_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.methods_button.setObjectName("methods_button")
        self.help_button = QtWidgets.QPushButton(home_window)
        self.help_button.setGeometry(QtCore.QRect(230, 560, 191, 61))
        self.help_button.setAcceptDrops(False)
        self.help_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.help_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.help_button.setObjectName("help_button")
        self.online_button = QtWidgets.QPushButton(home_window)
        self.online_button.setGeometry(QtCore.QRect(440, 560, 191, 61))
        self.online_button.setAcceptDrops(False)
        self.online_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.online_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.online_button.setObjectName("online_button")
        self.about_button = QtWidgets.QPushButton(home_window)
        self.about_button.setGeometry(QtCore.QRect(650, 560, 191, 61))
        self.about_button.setAcceptDrops(False)
        self.about_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.about_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.about_button.setObjectName("about_button")
        self.label = QtWidgets.QLabel(home_window)
        self.label.setGeometry(QtCore.QRect(180, 30, 500, 500))
        self.label.setStyleSheet("background-image: url(:/images/logo_numerikiando.png);")
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(home_window)
        QtCore.QMetaObject.connectSlotsByName(home_window)

    def retranslateUi(self, home_window):
        _translate = QtCore.QCoreApplication.translate
        home_window.setWindowTitle(_translate("home_window", "Form"))
        self.methods_button.setText(_translate("home_window", "Numerical methods"))
        self.help_button.setText(_translate("home_window", "Help"))
        self.online_button.setText(_translate("home_window", "Online help"))
        self.about_button.setText(_translate("home_window", "About us"))
import link_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    home_window = QtWidgets.QWidget()
    ui = Ui_home_window()
    ui.setupUi(home_window)
    home_window.show()
    sys.exit(app.exec_())
