# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/incremental_searches_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_incremental_searches(object):
    def setupUi(self, incremental_searches):
        incremental_searches.setObjectName("incremental_searches")
        incremental_searches.resize(900, 700)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        incremental_searches.setPalette(palette)
        self.label = QtWidgets.QLabel(incremental_searches)
        self.label.setGeometry(QtCore.QRect(70, 70, 771, 161))
        self.label.setStyleSheet("background-image: url(:/images/Banner10.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.f_input = QtWidgets.QTextEdit(incremental_searches)
        self.f_input.setGeometry(QtCore.QRect(70, 410, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.f_input.setFont(font)
        self.f_input.setObjectName("f_input")
        self.delta_input = QtWidgets.QTextEdit(incremental_searches)
        self.delta_input.setGeometry(QtCore.QRect(530, 410, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.delta_input.setFont(font)
        self.delta_input.setObjectName("delta_input")
        self.distance_input = QtWidgets.QTextEdit(incremental_searches)
        self.distance_input.setGeometry(QtCore.QRect(640, 410, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.distance_input.setFont(font)
        self.distance_input.setObjectName("distance_input")
        self.n_input = QtWidgets.QTextEdit(incremental_searches)
        self.n_input.setGeometry(QtCore.QRect(750, 410, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.n_input.setFont(font)
        self.n_input.setObjectName("n_input")
        self.label_2 = QtWidgets.QLabel(incremental_searches)
        self.label_2.setGeometry(QtCore.QRect(230, 360, 81, 41))
        self.label_2.setStyleSheet("background-image: url(:/images/function.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(incremental_searches)
        self.label_3.setGeometry(QtCore.QRect(530, 360, 81, 41))
        self.label_3.setStyleSheet("background-image: url(:/images/delta.png);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Designer\\../UserInterface/Util/Images/delta.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(incremental_searches)
        self.label_4.setGeometry(QtCore.QRect(640, 360, 81, 41))
        self.label_4.setStyleSheet("background-image: url(:/images/x0.png);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Designer\\../UserInterface/Util/Images/x0.png"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(incremental_searches)
        self.label_5.setGeometry(QtCore.QRect(750, 360, 81, 41))
        self.label_5.setStyleSheet("background-image: url(:/images/n.png);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Designer\\../UserInterface/Util/Images/n.png"))
        self.label_5.setObjectName("label_5")
        self.run_button = QtWidgets.QPushButton(incremental_searches)
        self.run_button.setGeometry(QtCore.QRect(410, 530, 131, 51))
        self.run_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.run_button.setObjectName("run_button")

        self.retranslateUi(incremental_searches)
        QtCore.QMetaObject.connectSlotsByName(incremental_searches)

    def retranslateUi(self, incremental_searches):
        _translate = QtCore.QCoreApplication.translate
        incremental_searches.setWindowTitle(_translate("incremental_searches", "Form"))
        self.run_button.setText(_translate("incremental_searches", "Run Method"))
import link_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    incremental_searches = QtWidgets.QWidget()
    ui = Ui_incremental_searches()
    ui.setupUi(incremental_searches)
    incremental_searches.show()
    sys.exit(app.exec_())
