# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/interpolation_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interpolation(object):
    def setupUi(self, interpolation):
        interpolation.setObjectName("interpolation")
        interpolation.resize(850, 650)
        interpolation.setMinimumSize(QtCore.QSize(850, 650))
        interpolation.setMaximumSize(QtCore.QSize(850, 650))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        interpolation.setPalette(palette)
        self.label = QtWidgets.QLabel(interpolation)
        self.label.setGeometry(QtCore.QRect(40, 30, 771, 161))
        self.label.setStyleSheet("background-image: url(:/images/Banner4.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.newtonint_button = QtWidgets.QPushButton(interpolation)
        self.newtonint_button.setGeometry(QtCore.QRect(250, 240, 361, 61))
        self.newtonint_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.newtonint_button.setObjectName("newtonint_button")
        self.lagrangeint_button = QtWidgets.QPushButton(interpolation)
        self.lagrangeint_button.setGeometry(QtCore.QRect(250, 350, 361, 61))
        self.lagrangeint_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.lagrangeint_button.setObjectName("lagrangeint_button")
        self.splines_button = QtWidgets.QPushButton(interpolation)
        self.splines_button.setGeometry(QtCore.QRect(250, 460, 361, 61))
        self.splines_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.splines_button.setObjectName("splines_button")
        self.back_button = QtWidgets.QPushButton(interpolation)
        self.back_button.setGeometry(QtCore.QRect(20, 580, 80, 50))
        self.back_button.setStyleSheet("background-color: rgb(0, 86, 145);\n"
"background-image: url(:/images/back.png);")
        self.back_button.setText("")
        self.back_button.setIconSize(QtCore.QSize(80, 50))
        self.back_button.setObjectName("back_button")
        self.home_button = QtWidgets.QPushButton(interpolation)
        self.home_button.setGeometry(QtCore.QRect(740, 580, 80, 50))
        self.home_button.setStyleSheet("background-color: rgb(0, 86, 145);\n"
"background-image: url(:/images/home.png);")
        self.home_button.setText("")
        self.home_button.setIconSize(QtCore.QSize(80, 50))
        self.home_button.setObjectName("home_button")
        self.vandermonde_button = QtWidgets.QPushButton(interpolation)
        self.vandermonde_button.setGeometry(QtCore.QRect(250, 570, 361, 61))
        self.vandermonde_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.vandermonde_button.setObjectName("vandermonde_button")

        self.retranslateUi(interpolation)
        QtCore.QMetaObject.connectSlotsByName(interpolation)

    def retranslateUi(self, interpolation):
        _translate = QtCore.QCoreApplication.translate
        interpolation.setWindowTitle(_translate("interpolation", "Form"))
        self.newtonint_button.setText(_translate("interpolation", "Newton\'s interpolating polynomial"))
        self.lagrangeint_button.setText(_translate("interpolation", "Lagrange interpolating polynomial"))
        self.splines_button.setText(_translate("interpolation", "Splines"))
        self.vandermonde_button.setText(_translate("interpolation", "Vandermonde"))
import link_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interpolation = QtWidgets.QWidget()
    ui = Ui_interpolation()
    ui.setupUi(interpolation)
    interpolation.show()
    sys.exit(app.exec_())
