# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/iterative_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_iterative(object):
    def setupUi(self, iterative):
        iterative.setObjectName("iterative")
        iterative.resize(850, 650)
        iterative.setMinimumSize(QtCore.QSize(850, 650))
        iterative.setMaximumSize(QtCore.QSize(850, 650))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        iterative.setPalette(palette)
        self.label = QtWidgets.QLabel(iterative)
        self.label.setGeometry(QtCore.QRect(40, 30, 771, 161))
        self.label.setStyleSheet("border-image: url(:/images/Banner7.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.jacobi_button = QtWidgets.QPushButton(iterative)
        self.jacobi_button.setGeometry(QtCore.QRect(250, 240, 361, 61))
        self.jacobi_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.jacobi_button.setObjectName("jacobi_button")
        self.gauss_button = QtWidgets.QPushButton(iterative)
        self.gauss_button.setGeometry(QtCore.QRect(250, 350, 361, 61))
        self.gauss_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.gauss_button.setObjectName("gauss_button")
        self.sor_button = QtWidgets.QPushButton(iterative)
        self.sor_button.setGeometry(QtCore.QRect(250, 460, 361, 61))
        self.sor_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.sor_button.setObjectName("sor_button")
        self.back_button = QtWidgets.QPushButton(iterative)
        self.back_button.setGeometry(QtCore.QRect(20, 580, 80, 50))
        self.back_button.setStyleSheet("background-color: rgb(0, 86, 145);\n"
"background-image: url(:/images/back.png);")
        self.back_button.setText("")
        self.back_button.setIconSize(QtCore.QSize(80, 50))
        self.back_button.setObjectName("back_button")
        self.home_button = QtWidgets.QPushButton(iterative)
        self.home_button.setGeometry(QtCore.QRect(740, 580, 80, 50))
        self.home_button.setStyleSheet("background-color: rgb(0, 86, 145);\n"
"background-image: url(:/images/home.png);")
        self.home_button.setText("")
        self.home_button.setIconSize(QtCore.QSize(80, 50))
        self.home_button.setObjectName("home_button")

        self.retranslateUi(iterative)
        QtCore.QMetaObject.connectSlotsByName(iterative)

    def retranslateUi(self, iterative):
        _translate = QtCore.QCoreApplication.translate
        iterative.setWindowTitle(_translate("iterative", "Form"))
        self.jacobi_button.setText(_translate("iterative", "Jacobi"))
        self.gauss_button.setText(_translate("iterative", "Gauss - Seidel"))
        self.sor_button.setText(_translate("iterative", "SOR"))
import link_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    iterative = QtWidgets.QWidget()
    ui = Ui_iterative()
    ui.setupUi(iterative)
    iterative.show()
    sys.exit(app.exec_())
