# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/linear_spline_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_linear_spline(object):
    def setupUi(self, linear_spline):
        linear_spline.setObjectName("linear_spline")
        linear_spline.resize(900, 700)
        linear_spline.setMinimumSize(QtCore.QSize(900, 700))
        linear_spline.setMaximumSize(QtCore.QSize(900, 700))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        linear_spline.setPalette(palette)
        self.label = QtWidgets.QLabel(linear_spline)
        self.label.setGeometry(QtCore.QRect(60, 30, 771, 151))
        self.label.setStyleSheet("background-image: url(:/images/linear_spline_banner.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(linear_spline)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 81, 41))
        self.label_5.setStyleSheet("background-image: url(:/images/n.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.n_input = QtWidgets.QTextEdit(linear_spline)
        self.n_input.setGeometry(QtCore.QRect(120, 200, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.n_input.setFont(font)
        self.n_input.setObjectName("n_input")
        self.vector_button = QtWidgets.QPushButton(linear_spline)
        self.vector_button.setGeometry(QtCore.QRect(230, 200, 171, 51))
        self.vector_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.vector_button.setObjectName("vector_button")
        self.run_button = QtWidgets.QPushButton(linear_spline)
        self.run_button.setGeometry(QtCore.QRect(380, 630, 151, 51))
        self.run_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.run_button.setObjectName("run_button")

        self.retranslateUi(linear_spline)
        QtCore.QMetaObject.connectSlotsByName(linear_spline)

    def retranslateUi(self, linear_spline):
        _translate = QtCore.QCoreApplication.translate
        linear_spline.setWindowTitle(_translate("linear_spline", "Form"))
        self.vector_button.setText(_translate("linear_spline", "Generate Vectors"))
        self.run_button.setText(_translate("linear_spline", "Run method"))
import link_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    linear_spline = QtWidgets.QWidget()
    ui = Ui_linear_spline()
    ui.setupUi(linear_spline)
    linear_spline.show()
    sys.exit(app.exec_())
