# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/linear_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_linear(object):
    def setupUi(self, linear):
        linear.setObjectName("linear")
        linear.resize(850, 650)
        linear.setMinimumSize(QtCore.QSize(850, 650))
        linear.setMaximumSize(QtCore.QSize(850, 650))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 74, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 74, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 74, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 74, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        linear.setPalette(palette)
        linear.setStyleSheet("")
        self.label = QtWidgets.QLabel(linear)
        self.label.setGeometry(QtCore.QRect(40, 30, 771, 161))
        self.label.setStyleSheet("background-image: url(:/images/Banner2.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Designer\\../UserInterface/Util/Images/Banner2.png"))
        self.label.setObjectName("label")
        self.lu_button = QtWidgets.QPushButton(linear)
        self.lu_button.setGeometry(QtCore.QRect(260, 270, 361, 51))
        self.lu_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.lu_button.setObjectName("lu_button")
        self.directf_button = QtWidgets.QPushButton(linear)
        self.directf_button.setGeometry(QtCore.QRect(260, 370, 361, 51))
        self.directf_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.directf_button.setObjectName("directf_button")
        self.iterative_button = QtWidgets.QPushButton(linear)
        self.iterative_button.setGeometry(QtCore.QRect(260, 470, 361, 51))
        self.iterative_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.iterative_button.setObjectName("iterative_button")
        self.gaussian_button = QtWidgets.QPushButton(linear)
        self.gaussian_button.setGeometry(QtCore.QRect(260, 570, 361, 51))
        self.gaussian_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.gaussian_button.setObjectName("gaussian_button")
        self.back_button = QtWidgets.QPushButton(linear)
        self.back_button.setGeometry(QtCore.QRect(20, 580, 80, 50))
        self.back_button.setStyleSheet("background-color: rgb(0, 86, 145);\n"
"background-image: url(:/images/back.png);")
        self.back_button.setText("")
        self.back_button.setIconSize(QtCore.QSize(80, 50))
        self.back_button.setObjectName("back_button")
        self.home_button = QtWidgets.QPushButton(linear)
        self.home_button.setGeometry(QtCore.QRect(740, 580, 80, 50))
        self.home_button.setStyleSheet("background-color: rgb(0, 86, 145);\n"
"background-image: url(:/images/home.png);")
        self.home_button.setText("")
        self.home_button.setIconSize(QtCore.QSize(80, 50))
        self.home_button.setObjectName("home_button")

        self.retranslateUi(linear)
        QtCore.QMetaObject.connectSlotsByName(linear)

    def retranslateUi(self, linear):
        _translate = QtCore.QCoreApplication.translate
        linear.setWindowTitle(_translate("linear", "Form"))
        self.lu_button.setText(_translate("linear", "LU Factoring"))
        self.directf_button.setText(_translate("linear", "Direct Factoring"))
        self.iterative_button.setText(_translate("linear", "Iterative Methods"))
        self.gaussian_button.setText(_translate("linear", "Gaussian Elimination"))
import link_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    linear = QtWidgets.QWidget()
    ui = Ui_linear()
    ui.setupUi(linear)
    linear.show()
    sys.exit(app.exec_())
