# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/lu_factoring_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lu_factoring(object):
    def setupUi(self, lu_factoring):
        lu_factoring.setObjectName("lu_factoring")
        lu_factoring.resize(850, 650)
        lu_factoring.setMinimumSize(QtCore.QSize(850, 650))
        lu_factoring.setMaximumSize(QtCore.QSize(850, 650))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        lu_factoring.setPalette(palette)
        self.label = QtWidgets.QLabel(lu_factoring)
        self.label.setGeometry(QtCore.QRect(40, 30, 771, 161))
        self.label.setStyleSheet("background-image: url(:/images/Banner5.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.simplelu_button = QtWidgets.QPushButton(lu_factoring)
        self.simplelu_button.setGeometry(QtCore.QRect(250, 260, 371, 61))
        self.simplelu_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 16px;\n"
"")
        self.simplelu_button.setObjectName("simplelu_button")
        self.partiallu_button = QtWidgets.QPushButton(lu_factoring)
        self.partiallu_button.setGeometry(QtCore.QRect(250, 410, 371, 61))
        self.partiallu_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 16px;\n"
"")
        self.partiallu_button.setObjectName("partiallu_button")
        self.back_button = QtWidgets.QPushButton(lu_factoring)
        self.back_button.setGeometry(QtCore.QRect(20, 580, 80, 50))
        self.back_button.setStyleSheet("background-color: rgb(0, 86, 145);\n"
"background-image: url(:/images/back.png);")
        self.back_button.setText("")
        self.back_button.setIconSize(QtCore.QSize(80, 50))
        self.back_button.setObjectName("back_button")
        self.home_button = QtWidgets.QPushButton(lu_factoring)
        self.home_button.setGeometry(QtCore.QRect(740, 580, 80, 50))
        self.home_button.setStyleSheet("background-color: rgb(0, 86, 145);\n"
"border-image: url(:/images/home.png);")
        self.home_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Designer\\../UserInterface/Util/Images/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_button.setIcon(icon)
        self.home_button.setIconSize(QtCore.QSize(80, 50))
        self.home_button.setObjectName("home_button")

        self.retranslateUi(lu_factoring)
        QtCore.QMetaObject.connectSlotsByName(lu_factoring)

    def retranslateUi(self, lu_factoring):
        _translate = QtCore.QCoreApplication.translate
        lu_factoring.setWindowTitle(_translate("lu_factoring", "Form"))
        self.simplelu_button.setText(_translate("lu_factoring", "Simple LU"))
        self.partiallu_button.setText(_translate("lu_factoring", "Partial LU"))
import link_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    lu_factoring = QtWidgets.QWidget()
    ui = Ui_lu_factoring()
    ui.setupUi(lu_factoring)
    lu_factoring.show()
    sys.exit(app.exec_())
