# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/lu_simple_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lu_simple_window(object):
    def setupUi(self, lu_simple_window):
        lu_simple_window.setObjectName("lu_simple_window")
        lu_simple_window.resize(900, 700)
        lu_simple_window.setMinimumSize(QtCore.QSize(900, 700))
        lu_simple_window.setMaximumSize(QtCore.QSize(900, 700))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        lu_simple_window.setPalette(palette)
        self.label = QtWidgets.QLabel(lu_simple_window)
        self.label.setGeometry(QtCore.QRect(60, 20, 771, 161))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(lu_simple_window)
        self.label_2.setGeometry(QtCore.QRect(90, 210, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.n_input = QtWidgets.QTextEdit(lu_simple_window)
        self.n_input.setGeometry(QtCore.QRect(220, 210, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.n_input.setFont(font)
        self.n_input.setObjectName("n_input")
        self.matrix_button = QtWidgets.QPushButton(lu_simple_window)
        self.matrix_button.setGeometry(QtCore.QRect(370, 200, 171, 51))
        self.matrix_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.matrix_button.setObjectName("matrix_button")
        self.run_button = QtWidgets.QPushButton(lu_simple_window)
        self.run_button.setGeometry(QtCore.QRect(380, 630, 151, 51))
        self.run_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.run_button.setObjectName("run_button")

        self.retranslateUi(lu_simple_window)
        QtCore.QMetaObject.connectSlotsByName(lu_simple_window)

    def retranslateUi(self, lu_simple_window):
        _translate = QtCore.QCoreApplication.translate
        lu_simple_window.setWindowTitle(_translate("lu_simple_window", "Form"))
        self.label.setText(_translate("lu_simple_window", "xd"))
        self.label_2.setText(_translate("lu_simple_window", "N:"))
        self.matrix_button.setText(_translate("lu_simple_window", "Generate Matrix"))
        self.run_button.setText(_translate("lu_simple_window", "Run method"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    lu_simple_window = QtWidgets.QWidget()
    ui = Ui_lu_simple_window()
    ui.setupUi(lu_simple_window)
    lu_simple_window.show()
    sys.exit(app.exec_())
