# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/matrix_answer_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_matrix_answer(object):
    def setupUi(self, matrix_answer):
        matrix_answer.setObjectName("matrix_answer")
        matrix_answer.resize(700, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        matrix_answer.setPalette(palette)
        self.scrollArea = QtWidgets.QScrollArea(matrix_answer)
        self.scrollArea.setGeometry(QtCore.QRect(10, 30, 671, 551))
        self.scrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 669, 549))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_answer = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_answer.setFont(font)
        self.label_answer.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.label_answer.setText("")
        self.label_answer.setObjectName("label_answer")
        self.horizontalLayout.addWidget(self.label_answer)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(matrix_answer)
        QtCore.QMetaObject.connectSlotsByName(matrix_answer)

    def retranslateUi(self, matrix_answer):
        _translate = QtCore.QCoreApplication.translate
        matrix_answer.setWindowTitle(_translate("matrix_answer", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    matrix_answer = QtWidgets.QWidget()
    ui = Ui_matrix_answer()
    ui.setupUi(matrix_answer)
    matrix_answer.show()
    sys.exit(app.exec_())
