# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/matrix_answer_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_matrix_answer(object):
    def setupUi(self, matrix_answer):
        matrix_answer.setObjectName("matrix_answer")
        matrix_answer.resize(700, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        matrix_answer.setPalette(palette)
        self.label_answer = QtWidgets.QLabel(matrix_answer)
        self.label_answer.setGeometry(QtCore.QRect(30, 40, 641, 541))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_answer.setFont(font)
        self.label_answer.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.label_answer.setText("")
        self.label_answer.setObjectName("label_answer")

        self.retranslateUi(matrix_answer)
        QtCore.QMetaObject.connectSlotsByName(matrix_answer)

    def retranslateUi(self, matrix_answer):
        _translate = QtCore.QCoreApplication.translate
        matrix_answer.setWindowTitle(_translate("matrix_answer", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    matrix_answer = QtWidgets.QWidget()
    ui = Ui_matrix_answer()
    ui.setupUi(matrix_answer)
    matrix_answer.show()
    sys.exit(app.exec_())
