# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/methods_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_methods_window(object):
    def setupUi(self, methods_window):
        methods_window.setObjectName("methods_window")
        methods_window.setEnabled(True)
        methods_window.resize(850, 650)
        methods_window.setMinimumSize(QtCore.QSize(850, 650))
        methods_window.setMaximumSize(QtCore.QSize(850, 650))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(250, 19, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 19, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 19, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        methods_window.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        methods_window.setFont(font)
        methods_window.setAutoFillBackground(True)
        methods_window.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(methods_window)
        self.centralwidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget.setObjectName("centralwidget")
        self.nonlinear_button = QtWidgets.QPushButton(self.centralwidget)
        self.nonlinear_button.setGeometry(QtCore.QRect(210, 290, 451, 61))
        self.nonlinear_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.nonlinear_button.setObjectName("nonlinear_button")
        self.interpolation_button = QtWidgets.QPushButton(self.centralwidget)
        self.interpolation_button.setGeometry(QtCore.QRect(210, 490, 451, 61))
        self.interpolation_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.interpolation_button.setObjectName("interpolation_button")
        self.linear_button = QtWidgets.QPushButton(self.centralwidget)
        self.linear_button.setGeometry(QtCore.QRect(210, 390, 451, 61))
        self.linear_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.linear_button.setObjectName("linear_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 771, 161))
        self.label.setStyleSheet("background-image: url(:/images/Banner1.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        methods_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(methods_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 21))
        self.menubar.setObjectName("menubar")
        methods_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(methods_window)
        self.statusbar.setObjectName("statusbar")
        methods_window.setStatusBar(self.statusbar)

        self.retranslateUi(methods_window)
        QtCore.QMetaObject.connectSlotsByName(methods_window)

    def retranslateUi(self, methods_window):
        _translate = QtCore.QCoreApplication.translate
        methods_window.setWindowTitle(_translate("methods_window", "MainWindow"))
        self.nonlinear_button.setText(_translate("methods_window", " Numerical solution of nonlinear equation"))
        self.interpolation_button.setText(_translate("methods_window", "Interpolation"))
        self.linear_button.setText(_translate("methods_window", "Numerical solution of systems of linear equations"))
import link_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    methods_window = QtWidgets.QMainWindow()
    ui = Ui_methods_window()
    ui.setupUi(methods_window)
    methods_window.show()
    sys.exit(app.exec_())
