# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/nonlinear_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_nonlinear(object):
    def setupUi(self, nonlinear):
        nonlinear.setObjectName("nonlinear")
        nonlinear.resize(850, 650)
        nonlinear.setMinimumSize(QtCore.QSize(850, 650))
        nonlinear.setMaximumSize(QtCore.QSize(850, 650))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        nonlinear.setPalette(palette)
        self.label = QtWidgets.QLabel(nonlinear)
        self.label.setGeometry(QtCore.QRect(40, 30, 771, 161))
        self.label.setStyleSheet("background-image: url(:/images/Banner3.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Designer\\../UserInterface/Util/Images/Banner3.png"))
        self.label.setObjectName("label")
        self.incremental_button = QtWidgets.QPushButton(nonlinear)
        self.incremental_button.setGeometry(QtCore.QRect(240, 250, 361, 51))
        self.incremental_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.incremental_button.setObjectName("incremental_button")
        self.bisection_button = QtWidgets.QPushButton(nonlinear)
        self.bisection_button.setGeometry(QtCore.QRect(240, 330, 361, 51))
        self.bisection_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.bisection_button.setObjectName("bisection_button")
        self.fixedp_button = QtWidgets.QPushButton(nonlinear)
        self.fixedp_button.setGeometry(QtCore.QRect(240, 410, 361, 51))
        self.fixedp_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.fixedp_button.setObjectName("fixedp_button")
        self.newton_button = QtWidgets.QPushButton(nonlinear)
        self.newton_button.setGeometry(QtCore.QRect(240, 490, 361, 51))
        self.newton_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.newton_button.setObjectName("newton_button")
        self.secant_button = QtWidgets.QPushButton(nonlinear)
        self.secant_button.setGeometry(QtCore.QRect(240, 570, 361, 51))
        self.secant_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.secant_button.setObjectName("secant_button")
        self.back_button = QtWidgets.QPushButton(nonlinear)
        self.back_button.setGeometry(QtCore.QRect(20, 580, 80, 50))
        self.back_button.setStyleSheet("background-color: rgb(0, 86, 145);\n"
"background-image: url(:/images/back.png);")
        self.back_button.setText("")
        self.back_button.setIconSize(QtCore.QSize(80, 50))
        self.back_button.setObjectName("back_button")
        self.home_button = QtWidgets.QPushButton(nonlinear)
        self.home_button.setGeometry(QtCore.QRect(740, 580, 80, 50))
        self.home_button.setStyleSheet("background-color: rgb(0, 86, 145);\n"
"background-image: url(:/images/home.png);")
        self.home_button.setText("")
        self.home_button.setIconSize(QtCore.QSize(80, 50))
        self.home_button.setObjectName("home_button")

        self.retranslateUi(nonlinear)
        QtCore.QMetaObject.connectSlotsByName(nonlinear)

    def retranslateUi(self, nonlinear):
        _translate = QtCore.QCoreApplication.translate
        nonlinear.setWindowTitle(_translate("nonlinear", "Form"))
        self.incremental_button.setText(_translate("nonlinear", "Incremental searches"))
        self.bisection_button.setText(_translate("nonlinear", "Bisection"))
        self.fixedp_button.setText(_translate("nonlinear", "Fixed Point"))
        self.newton_button.setText(_translate("nonlinear", "Newton"))
        self.secant_button.setText(_translate("nonlinear", "Secant"))
import link_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    nonlinear = QtWidgets.QWidget()
    ui = Ui_nonlinear()
    ui.setupUi(nonlinear)
    nonlinear.show()
    sys.exit(app.exec_())
