# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/partial_pivoting_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_partial_pivoting_window(object):
    def setupUi(self, partial_pivoting_window):
        partial_pivoting_window.setObjectName("partial_pivoting_window")
        partial_pivoting_window.resize(900, 700)
        partial_pivoting_window.setMinimumSize(QtCore.QSize(900, 700))
        partial_pivoting_window.setMaximumSize(QtCore.QSize(900, 700))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        partial_pivoting_window.setPalette(palette)
        self.label = QtWidgets.QLabel(partial_pivoting_window)
        self.label.setGeometry(QtCore.QRect(60, 20, 771, 161))
        self.label.setStyleSheet("background-image: url(:/images/PartialBanner.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(partial_pivoting_window)
        self.label_5.setGeometry(QtCore.QRect(90, 210, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-image: url(:/images/n.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.n_input = QtWidgets.QTextEdit(partial_pivoting_window)
        self.n_input.setGeometry(QtCore.QRect(220, 210, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.n_input.setFont(font)
        self.n_input.setObjectName("n_input")
        self.matrix_button = QtWidgets.QPushButton(partial_pivoting_window)
        self.matrix_button.setGeometry(QtCore.QRect(370, 200, 171, 51))
        self.matrix_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.matrix_button.setObjectName("matrix_button")
        self.run_button = QtWidgets.QPushButton(partial_pivoting_window)
        self.run_button.setGeometry(QtCore.QRect(380, 630, 151, 51))
        self.run_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.run_button.setObjectName("run_button")

        self.retranslateUi(partial_pivoting_window)
        QtCore.QMetaObject.connectSlotsByName(partial_pivoting_window)

    def retranslateUi(self, partial_pivoting_window):
        _translate = QtCore.QCoreApplication.translate
        partial_pivoting_window.setWindowTitle(_translate("partial_pivoting_window", "Form"))
        self.matrix_button.setText(_translate("partial_pivoting_window", "Generate Matrix"))
        self.run_button.setText(_translate("partial_pivoting_window", "Run method"))
import link_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    partial_pivoting_window = QtWidgets.QWidget()
    ui = Ui_partial_pivoting_window()
    ui.setupUi(partial_pivoting_window)
    partial_pivoting_window.show()
    sys.exit(app.exec_())
