# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/sor_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sor(object):
    def setupUi(self, sor):
        sor.setObjectName("sor")
        sor.resize(900, 700)
        sor.setMinimumSize(QtCore.QSize(900, 700))
        sor.setMaximumSize(QtCore.QSize(900, 700))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        sor.setPalette(palette)
        self.label = QtWidgets.QLabel(sor)
        self.label.setGeometry(QtCore.QRect(60, 20, 771, 161))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(sor)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 81, 41))
        self.label_5.setStyleSheet("background-image: url(:/images/n.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.n_input = QtWidgets.QTextEdit(sor)
        self.n_input.setGeometry(QtCore.QRect(120, 200, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.n_input.setFont(font)
        self.n_input.setObjectName("n_input")
        self.matrix_button = QtWidgets.QPushButton(sor)
        self.matrix_button.setGeometry(QtCore.QRect(230, 200, 171, 51))
        self.matrix_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.matrix_button.setObjectName("matrix_button")
        self.run_button = QtWidgets.QPushButton(sor)
        self.run_button.setGeometry(QtCore.QRect(380, 630, 151, 51))
        self.run_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.run_button.setObjectName("run_button")
        self.t_input = QtWidgets.QTextEdit(sor)
        self.t_input.setGeometry(QtCore.QRect(470, 200, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t_input.setFont(font)
        self.t_input.setObjectName("t_input")
        self.label_2 = QtWidgets.QLabel(sor)
        self.label_2.setGeometry(QtCore.QRect(420, 210, 61, 21))
        self.label_2.setObjectName("label_2")
        self.iter_input = QtWidgets.QTextEdit(sor)
        self.iter_input.setGeometry(QtCore.QRect(670, 200, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.iter_input.setFont(font)
        self.iter_input.setObjectName("iter_input")
        self.label_3 = QtWidgets.QLabel(sor)
        self.label_3.setGeometry(QtCore.QRect(620, 200, 51, 31))
        self.label_3.setObjectName("label_3")
        self.w_input = QtWidgets.QTextEdit(sor)
        self.w_input.setGeometry(QtCore.QRect(810, 200, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.w_input.setFont(font)
        self.w_input.setObjectName("w_input")
        self.label_w = QtWidgets.QLabel(sor)
        self.label_w.setGeometry(QtCore.QRect(790, 200, 21, 31))
        self.label_w.setObjectName("label_w")

        self.retranslateUi(sor)
        QtCore.QMetaObject.connectSlotsByName(sor)

    def retranslateUi(self, sor):
        _translate = QtCore.QCoreApplication.translate
        sor.setWindowTitle(_translate("sor", "Form"))
        self.label.setText(_translate("sor", "SOR"))
        self.matrix_button.setText(_translate("sor", "Generate Matrix"))
        self.run_button.setText(_translate("sor", "Run method"))
        self.label_2.setText(_translate("sor", "Toletance"))
        self.label_3.setText(_translate("sor", "Iterations"))
        self.label_w.setText(_translate("sor", "w"))
import link_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sor = QtWidgets.QWidget()
    ui = Ui_sor()
    ui.setupUi(sor)
    sor.show()
    sys.exit(app.exec_())
