# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/splines_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_splines(object):
    def setupUi(self, splines):
        splines.setObjectName("splines")
        splines.resize(850, 650)
        splines.setMinimumSize(QtCore.QSize(850, 650))
        splines.setMaximumSize(QtCore.QSize(850, 650))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 86, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        splines.setPalette(palette)
        self.label = QtWidgets.QLabel(splines)
        self.label.setGeometry(QtCore.QRect(40, 30, 771, 161))
        self.label.setStyleSheet("background-image: url(:/images/Banner8.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.linear_button = QtWidgets.QPushButton(splines)
        self.linear_button.setGeometry(QtCore.QRect(250, 230, 361, 61))
        self.linear_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.linear_button.setObjectName("linear_button")
        self.quadratic_button = QtWidgets.QPushButton(splines)
        self.quadratic_button.setGeometry(QtCore.QRect(250, 330, 361, 61))
        self.quadratic_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.quadratic_button.setObjectName("quadratic_button")
        self.cubric_button = QtWidgets.QPushButton(splines)
        self.cubric_button.setGeometry(QtCore.QRect(250, 430, 361, 61))
        self.cubric_button.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 86, 145);\n"
"border-radius: 12px;\n"
"")
        self.cubric_button.setObjectName("cubric_button")
        self.back_button = QtWidgets.QPushButton(splines)
        self.back_button.setGeometry(QtCore.QRect(20, 580, 80, 50))
        self.back_button.setStyleSheet("background-color: rgb(0, 86, 145);\n"
"background-image: url(:/images/back.png);")
        self.back_button.setText("")
        self.back_button.setIconSize(QtCore.QSize(80, 50))
        self.back_button.setObjectName("back_button")
        self.home_button = QtWidgets.QPushButton(splines)
        self.home_button.setGeometry(QtCore.QRect(740, 580, 80, 50))
        self.home_button.setStyleSheet("background-color: rgb(0, 86, 145);\n"
"background-image: url(:/images/home.png);")
        self.home_button.setText("")
        self.home_button.setIconSize(QtCore.QSize(80, 50))
        self.home_button.setObjectName("home_button")

        self.retranslateUi(splines)
        QtCore.QMetaObject.connectSlotsByName(splines)

    def retranslateUi(self, splines):
        _translate = QtCore.QCoreApplication.translate
        splines.setWindowTitle(_translate("splines", "Form"))
        self.linear_button.setText(_translate("splines", "Linear Spline"))
        self.quadratic_button.setText(_translate("splines", "Square Spline"))
        self.cubric_button.setText(_translate("splines", "Cubric Spline"))
import link_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    splines = QtWidgets.QWidget()
    ui = Ui_splines()
    ui.setupUi(splines)
    splines.show()
    sys.exit(app.exec_())
